apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: node
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: node
  sessionAffinity: None
  type: ClusterIP